#!/usr/bin/env bash

echo "==================="
echo "# NOTICE"
echo "# Please use goenv instead"
echo "==================="

sleep 1

VERSION="$1"
GVM_PATH="/usr/local/go/go$VERSION"
## NOTE
# In order to install new Go version, go to https://go.dev/dl and manually download tar.gz archive
# Add the version manually to the /usr/lib/go-<version>
#

echo -e "WARNING! This is not automatic installation tool. Please proceed with caution.\n"

if [ -z "$1" ]; then
   echo "Usage: $0 <version>"
   exit 1
fi
sleep 1

if [ -d "$GVM_PATH" ]; then
   echo "go version $VERSION is already installed at $GVM_PATH"
else
   echo "Commands to install new version:"
   echo "cd /tmp"
   echo "wget https://go.dev/dl/go$VERSION.linux-amd64.tar.gz"
   echo "mkdir -p $GVM_PATH"
   echo "tar -C $GVM_PATH -xzf go$VERSION.linux-amd64.tar.gz"
fi

echo ""
echo "To switch versions:" 
echo "sudo rm /usr/bin/go; sudo ln -s $GVM_PATH /usr/bin/go"
echo ""
echo "To verify that go is in PATH:"
echo "go version"
