#!/usr/bin/env bash

echo 'forge-std/=lib/forge-std/src/' > remappings.txt

for DEP in $(jq '.dependencies | keys[]' package.json); do
   # skip hardhad and JS specific imports - at least most popular ones
   if ! [[ "$DEP" =~ ^(.*hardhat.*|.*nomic.*|.*dotenv.*)$ ]]; then
      DEP_NORM="${DEP//\"}"
      echo "$DEP_NORM=node_modules/$DEP_NORM" >> remappings.txt
   fi
done
